"""Add paper_type, created_at, updated_at to Paper model

Revision ID: 66e39a3cba42
Revises: 
Create Date: 2025-07-09 17:20:10.529739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e39a3cba42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('paper_type', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('papers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'created_at')
    op.drop_column('papers', 'paper_type')
    # ### end Alembic commands ###
